name: Sync Vercel to Production

on:
  push:
    branches:
      - master

jobs:
  sync-vercel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        npm install -g vercel
        npm install

    - name: Sync Vercel to Production
      run: |
        git checkout production
        git pull origin master
        git push origin production